version: '3.8'

services:
  db:
    image: postgres:15
    container_name: attendencecheckin-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendencecheckin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendencecheckin-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/attendencecheckin
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: 